name: attendifyx
description:
publish_to:


environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/logo/logo.png
  image_dark: assets/logo/logo.png
  android_12:
    image: assets/logo/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/logo/logo.png
    icon_background_color_dark: "#121212"

    web: false

flutter:
  assets:
    - assets/logo/logo.png
    - assets/images/welcome_images/
    - assets/logo/
    - assets/images/signup_image.png
    - assets/images/dashboard/
  uses-material-design: true
